name: MyFinance
description: Finance overview for Home Assistant
version: 1.0.0
slug: myfinance
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  5000/tcp: 5000
image: ghcr.io/dandifac/myfinance:latest