name: MyFinance
version: "1.0.0"
slug: myfinance
description: Finance overview for Home Assistant
arch:
  - aarch64
  - amd64
  - arm64
init: false
image: "ghcr.io/danielgallik/myfinance"
startup: services
boot: manual
ingress: true
ports:
  5000/tcp: 5000